
# ---------------- Shared Network ----------------
networks:
  app-network:
    driver: bridge

# ---------------- Volumes ----------------
volumes:
  mysql_data:

# ---------------- Services ----------------
services:

  # ---------------- Kafka ----------------
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=OaVOPQ2bTzKqluD7Q2nxYw
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ---------------- Memcached ----------------
  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    networks:
      - app-network

  # ---------------- MySQL ----------------
  mysql:
    container_name: mysql
    image: mysql:9
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # ---------------- User Service ----------------
  user-service:
    container_name: user-service
    build: ./src/services/user-service
    env_file:
      - ./src/services/user-service/.env
    volumes:
      - ./src/services/user-service/src:/app/src
    depends_on:
      mysql:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    networks:
      - app-network

  # ---------------- Ride Service ----------------
  ride-service:
    container_name: ride-service
    build: ./src/services/ride-service
    env_file:
      - ./src/services/ride-service/.env
    volumes:
      - ./src/services/ride-service:/app
    depends_on:
      mysql:
        condition: service_started
      api-gateway:
        condition: service_started
      user-service:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - USER_SERVICE_URL=http://user-service:${USER_SERVICE_PORT}
    ports:
      - "${RIDE_SERVICE_PORT}:${RIDE_SERVICE_PORT}"
      - "9229:9229"
    command: npm run dev
    networks:
      - app-network

  # ---------------- Location Service ----------------
  location-service:
    container_name: location-service
    build: ./src/services/location-service
    env_file:
      - ./src/services/location-service/.env
    volumes:
      - ./src/services/location-service:/app
    depends_on:
      api-gateway:
        condition: service_started
#      user-service:
#        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - LOCATION_SERVICE_URL=${LOCATION_SERVICE_URL}
#      - USER_SERVICE_URL=http://user-service:${USER_SERVICE_PORT}
    ports:
      - "${LOCATION_SERVICE_PORT}:${LOCATION_SERVICE_PORT}"
#      - "9229:9229"
      - "8080:8080"
    command: npm run dev
    networks:
      - app-network

  # ---------------- Auth Service ----------------
  auth-service:
    container_name: auth-service
    build: ./src/services/auth-service
    env_file:
      - ./src/services/auth-service/.env
    volumes:
      - ./src/services/auth-service/src:/app/src
    depends_on:
      user-service:
        condition: service_started
      memcached:
        condition: service_started
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    networks:
      - app-network
      #
  # ---------------- Auth Service ----------------
  logging-service:
    container_name: logging-service
    build: ./src/services/logging-service
    volumes:
      - ./src/services/logging-service/src:/app/src
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "${LOGGING_SERVICE_PORT}:${LOGGING_SERVICE_PORT}"
    networks:
      - app-network

  # ---------------- API Gateway ----------------
  api-gateway:
    container_name: api-gateway
    build: ./src/services/api-gateway
    env_file:
      - ./src/services/api-gateway/.env
    environment:

      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}:${AUTH_SERVICE_PORT}
      - USER_SERVICE_URL=${USER_SERVICE_URL}:${USER_SERVICE_PORT}
      - RIDE_SERVICE_URL=${RIDE_SERVICE_URL}:${RIDE_SERVICE_PORT}
      - LOCATION_SERVICE_URL=${LOCATION_SERVICE_URL}:${LOCATION_SERVICE_PORT}

    volumes:
      - ./src/services/api-gateway/src:/app/src
    depends_on:
      user-service:
        condition: service_started
      auth-service:
        condition: service_started
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    networks:
      - app-network
